
name: 'hmda_data' 
version: '0.0.1'
require-dbt-version: "1.3.0"
config-version: 2

profile: 'snowflake-dw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  hmda_data:
    # Source-confirmed data, applies to all files under models/base/
    base:
      +materialized: view
    # Business-confirmed data, applies to all files under models/base/
    core:
      +materialized: table
